local clientURL =
"https://raw.githubusercontent.com/BlankAtom0/cc-crafter-os/refs/heads/main/src/pocket.lua?token=GHSAT0AAAAAAEAEZXJHQF3FM7RV7S5YDIJE2SDYYSA"
local startupURL = ""
local updaterURL = ""

local function printHeader(text)
    print()
    print(("=== %s ==="):format(text))
end

local function ask(prompt, default)
    write(prompt)
    if default ~= nil then write(" [" .. tostring(default) .. "]") end
    write(": ")
    local input = read()
    if input == "" and default ~= nil then return default end
    return input
end

local function askNumber(prompt, default)
    while true do
        local raw = ask(prompt, default)
        local n = tonumber(raw)
        if n then return n end
        print("Please enter a number.")
    end
end

local function askYesNo(prompt, default)
    local d = default and "Y/n" or "y/N"
    while true do
        local raw = ask(prompt .. " (" .. d .. ")", "")
        if raw == "" then return default end
        raw = raw:lower()
        if raw == "y" or raw == "yes" then return true end
        if raw == "n" or raw == "no" then return false end
        print("Please answer y or n.")
    end
end


local function installConfig(channel, clientNo)
    local config = {
        STOCK_CHANNEL = channel,
        ORDER_CHANNEL = channel + 1,
        CLIENT_CHANNEL = channel + 2 + clientNo,
        SCAN_DELAY = 5,
        STALE_TIMEOUT = 15,
    }
    return config
end

local function main()
    printHeader("Installer")
    local channel = askNumber("Enter the stock channel number", 1)
    local clientNo = askNumber("Enter the client number", 1)
    local config = installConfig(channel, clientNo)
    printHeader("Configuration")
    local configContents = string.format([[
        -- ======================================================
        -- Shared Config    |    config.cfg
        -- Generated by installer.lua.
        -- ======================================================

        return {
            STOCK_CHANNEL = %d,
            ORDER_CHANNEL = %d,
            CLIENT_CHANNEL = %d,
            SCAN_DELAY = %d,
            STALE_TIMEOUT = %d,
        }
        ]], config.STOCK_CHANNEL, config.ORDER_CHANNEL, config.CLIENT_CHANNEL, config.SCAN_DELAY, config.STALE_TIMEOUT)

    if fs.exists("config.cfg") then
        print("Config file already exists.")
        return
    else
        local configFile = io.open("config.cfg", "w")
        if not configFile then
            print("Failed to open config file.")
            return
        end
        configFile:write(configContents)
        configFile:close()
    end

    print("Config file saved.")

    printHeader("Installing Client")

    local response = http.get(clientURL)
    if not response then
        print("Failed to download client.")
        return
    end
    if fs.exists("client.lua") then
        os.remove("client.lua")
    end

    local clientFile = io.open("client.lua", "w")
    if not clientFile then
        print("Failed to open client file.")
        return
    end
    clientFile:write(response.readAll())
    clientFile:close()

    print("Client installed.")

    printHeader("Installing Startup Script")

    local response = http.get(startupURL)
    if not response then
        print("Failed to download startup script.")
        return
    end
    if fs.exists("startup.lua") then
        os.remove("startup.lua")
    end

    local startupFile = io.open("startup.lua", "w")
    if not startupFile then
        print("Failed to open startup file.")
        return
    end
    startupFile:write(response.readAll())
    startupFile:close()

    print("Startup script installed.")

    printHeader("Installing Updater")

    local response = http.get(updaterURL)
    if not response then
        print("Failed to download updater.")
        return
    end
    if fs.exists("updater.lua") then
        os.remove("updater.lua")
    end

    local updaterFile = io.open("updater.lua", "w")
    if not updaterFile then
        print("Failed to open updater file.")
        return
    end
    updaterFile:write(response.readAll())
    updaterFile:close()

    print("Updater installed.")

    printHeader("Install Complete")
    print("Client installed successfully.")

    print("Restart computer to continue...")
end
